Bug fix in OpHitFinder that should be backward compatible
LArSoft/larana pull request #13
Opened 2021-09-20 19:11 UTC by PetrilloAtWork

This is a request originating from @drinkingkazu. The description in his words follows.

> This change concerns `PedAlgoRmsSlider` and improves pedestal estimation of optical waveforms in ICARUS detectors. `CatchSaturation` is a newly added configuration parameter and set to `false` by default, in which case the algorithm performs same as before this change. When it is set to `true`, the algorithm enables a newly added feature, which handles a waveform saturation when happened in the middle. Here, a "waveform saturation" is defined as the ADC value reaching its minimum (`0`) or maximum (`4095` if 12-bit ADC). When saturation takes place, sometimes (often) ADC value stays at the same value (`0` in case of ICARUS for negative polarity waveforms). `PedAlgoRmsSlider` uses RMS of consecutive (in temporal direction) ADC values to identify the presence of a pulse. A pedestal is estimated from ADCs whose RMS, computed with the `neighborADCs`, takes a small value (i.e. below set threshold). This approach is vulnerable to saturated regions of a waveform since RMS is 0 in those regions. For regions that carry large(r than set threshold) RMS values, pedestal is estimated by linearly extrapolating the regions before and after. If the bad region happens at the start or end of a waveform, the first/last good pedestal value is copied and used in those regions since an extrapolation requires two good pedestal regions sandwiching the bad region. The introduced change define a "saturation region" by two newly introduced configuration parameters, `SatRangeMax` and `SatRangeMin`, and avoid using any ADC values within that region as a "good pedestal" candidate.

As pointed in the description, the default value of the new `CatchSaturation` parameter (`false`) is expected to reproduce the behaviour that existed before the changes, qualifying this as a **non-breaking change**.

2021-09-20 19:11 UTC, FNALbuild commented
A new Pull Request was created by  @PetrilloAtWork (Gianluca Petrillo) for develop.

It involves the following packages:

larana


@LArSoft/level-1-managers, @LArSoft/level-2-managers can you please review it and eventually sign? Thanks.

cms-bot commands are listed <a href="https://cdcvs.fnal.gov/redmine/projects/larsoft/wiki/Pull_request_comments_that_trigger_CI_actions">here</a>

2021-09-20 19:11 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2021-09-20 19:11 UTC, FNALbuild commented
+code-checks  
 for details see 
 https://buildmaster.fnal.gov/buildmaster/job/GithubIntegration/job/run-pr-code-checks//1005/console

2021-09-22 04:17 UTC, FNALbuild commented
Pull request #13 was updated. @LArSoft/level-1-managers, @LArSoft/level-2-managers can you please check and sign again.

2021-09-22 04:17 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2021-09-22 04:17 UTC, FNALbuild commented
+code-checks  
 for details see 
 https://buildmaster.fnal.gov/buildmaster/job/GithubIntegration/job/run-pr-code-checks//1009/console

2021-09-27 16:37 UTC, knoepfel requested changes
A few comments:

- There are some whitespace issues with this PR (e.g. inconsistent indentation).  Please address those.
- Please replace all `std::cout` uses with `mf::LogXYZ(...)` calls enabling users to disable messages via their framework-job cofiguration.

2021-09-27 16:37 UTC, knoepfel commented on larana/OpticalDetector/OpHitFinder/PedAlgoRmsSlider.cxx
> +      std::cout << "Catching saturation enabled" << std::endl;
Please switch all `std::cout` statements to `mf::LogXYZ(...)` ones.

2021-10-15 17:47 UTC, drinkingkazu commented on larana/OpticalDetector/OpHitFinder/PedAlgoRmsSlider.cxx
> +      std::cout << "Catching saturation enabled" << std::endl;
@knoepfel 
* I would like to refrain from "replace all" `std::cout` usage as I prefer to work on this code outside larsoft and it just makes it more cumbersome. If you are talking about this specific line, and not "all", I am happy to comment out and avoid logging the state of this feature enabled/diabled for users.
* For the indentations, I assume you mean within this code itself, and you did not mean this code being inconsistent w/ the rest of larsoft (please correct me if I'm wrong, I think it may be inconsistent in either case and was not clear). If that's a strong policy to avoid/delay merge, I am happy to modify when I find time later. If you could do it so it fits in the existing policy, that would be wonderful.

Tagging @SFBayLaser @PetrilloAtWork in this reply for the record!

2021-10-18 15:03 UTC, SFBayLaser commented on larana/OpticalDetector/OpHitFinder/PedAlgoRmsSlider.cxx
> +      std::cout << "Catching saturation enabled" << std::endl;
Would like to have this in this week's LArSoft release, what is possibility?

2021-10-18 16:48 UTC, knoepfel commented on larana/OpticalDetector/OpHitFinder/PedAlgoRmsSlider.cxx
> +      std::cout << "Catching saturation enabled" << std::endl;
@drinkingkazu, we are willing to leave the `std::cout` statements so long as you:

- Guard all `std::cout` statements with a `_verbose` flag (including lines 45-46 above and in the `OpHitFinder` module)
- Change the default value of `_verbose` to `false`

We also ask that *for the code you added* you find the time to make its indentation consistent with the surrounding code.  This should not take long.

@SFBayLaser, yes, this PR could likely go in this week assuming the issues we raised are addressed.

2021-10-20 16:38 UTC, FNALbuild commented
Pull request #13 was updated. @LArSoft/level-1-managers, @LArSoft/level-2-managers can you please check and sign again.

2021-10-20 16:38 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2021-10-20 16:38 UTC, FNALbuild commented
+code-checks  
 for details see 
 https://buildmaster.fnal.gov/buildmaster/job/GithubIntegration/job/run-pr-code-checks//1045/console

2021-10-21 16:16 UTC, lgarren commented
trigger build

2021-10-21 16:16 UTC, FNALbuild commented
The tests are being triggered in jenkins.

2021-10-21 16:41 UTC, knoepfel commented
Thanks, @drinkingkazu.  Just a couple more issues:

- The `OpHitFinder_module.cc` has unguarded `std::cout` statements.  Please surround them with a (configurable) verbosity flag as you did in `PedAlgoRmsSlider`.
- There are still indentation issues with this PR.  Please ensure that tabs are converted to spaces and that the indentation of the code you introduce is consistent with the code that surrounds your contributions.

2021-10-21 16:46 UTC, FNALbuild commented
+LArSoft tests OK on slf7 for c7:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/13057&builds= 
 +build

2021-10-21 16:50 UTC, FNALbuild commented
+LArSoft tests OK on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/13058&builds= 
 +build

2021-10-21 17:01 UTC, FNALbuild commented
-lariat failed on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:lariat/view_builds/index?offset=0&builds=lariat_ci/5968&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/13058&builds=

2021-10-21 17:04 UTC, FNALbuild commented
+argoneut tests OK on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:argoneut/view_builds/index?offset=0&builds=argoneut_ci/6220&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/13058&builds=

2021-10-21 17:51 UTC, FNALbuild commented
-dune tests warning on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:dune/view_builds/index?offset=0&builds=dune_ci/12085&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/13058&builds=

2021-10-21 18:10 UTC, FNALbuild commented
-uboone tests warning on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:uboone/view_builds/index?offset=0&builds=uboone_ci/6686&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/13058&builds=

2021-10-21 21:12 UTC, FNALbuild commented
-icarus tests failed on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:icarus/view_builds/index?offset=0&builds=icarus_ci/2786&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/13058&builds=

2021-10-21 21:12 UTC, FNALbuild commented
-sbnd tests failed on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:sbnd/view_builds/index?offset=0&builds=sbnd_ci/7480&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/13058&builds=

2021-10-25 15:49 UTC, knoepfel commented
@drinkingkazu, see https://github.com/LArSoft/larana/pull/13#issuecomment-948790992.

2021-11-05 19:42 UTC, knoepfel commented
Closed in favor of PR #14.

2021-11-05 19:42 UTC, closed without merging