Module to extract information from photon detector
LArSoft/larana pull request #22
Opened 2022-11-17 16:49 UTC by Healthborn

Used for training neural network for photon fast simulation. Files to commit include the module and the standard fcl.

2022-11-17 16:49 UTC, FNALbuild commented
A new Pull Request was created by  @Healthborn  for develop.

It involves the following packages:

larana


@LArSoft/level-1-managers, @LArSoft/level-2-managers can you please review it and eventually sign? Thanks.

cms-bot commands are listed <a href="https://cdcvs.fnal.gov/redmine/projects/larsoft/wiki/Pull_request_comments_that_trigger_CI_actions">here</a>

2022-11-17 16:49 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2022-11-17 16:49 UTC, FNALbuild commented
-code-checks
Pull request failed code-formatting checks. Please ensure that `cetmodules` has been setup and execute the following command from the top-level directory of your repository:

```
format-code \
  larana/OpticalDetector/PhotonInf_module.cc
```
Then commit the changes and push them to your PR branch.

2022-11-17 17:13 UTC, FNALbuild commented
Pull request #22 was updated. @LArSoft/level-1-managers, @LArSoft/level-2-managers can you please check and sign again.

2022-11-17 17:13 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2022-11-17 17:14 UTC, FNALbuild commented
-code-checks
Pull request failed code-formatting checks. Please ensure that `cetmodules` has been setup and execute the following command from the top-level directory of your repository:

```
format-code \
  larana/OpticalDetector/PhotonInf_module.cc
```
Then commit the changes and push them to your PR branch.

2022-11-17 17:16 UTC, FNALbuild commented
Pull request #22 was updated. @LArSoft/level-1-managers, @LArSoft/level-2-managers can you please check and sign again.

2022-11-17 17:16 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2022-11-17 17:16 UTC, FNALbuild commented
-code-checks
Pull request failed code-formatting checks. Please ensure that `cetmodules` has been setup and execute the following command from the top-level directory of your repository:

```
format-code \
  larana/OpticalDetector/PhotonInf_module.cc
```
Then commit the changes and push them to your PR branch.

2022-11-17 17:37 UTC, FNALbuild commented
Pull request #22 was updated. @LArSoft/level-1-managers, @LArSoft/level-2-managers can you please check and sign again.

2022-11-17 17:37 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2022-11-17 17:37 UTC, FNALbuild commented
+code-checks

2022-11-21 16:34 UTC, knoepfel commented
trigger build

2022-11-21 16:34 UTC, FNALbuild commented
The tests are being triggered in jenkins.

2022-11-21 17:10 UTC, FNALbuild commented
+LArSoft tests OK on slf7 for c7:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17600&builds= 
 +build

2022-11-21 17:12 UTC, FNALbuild commented
+LArSoft tests OK on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17601&builds= 
 +build

2022-11-21 17:25 UTC, FNALbuild commented
-lariat failed on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:lariat/view_builds/index?offset=0&builds=lariat_ci/7371&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17601&builds=

2022-11-21 17:26 UTC, FNALbuild commented
-dune tests tests failed on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:dune/view_builds/index?offset=0&builds=dune_ci/14435&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17601&builds=

2022-11-21 17:34 UTC, FNALbuild commented
-uboone tests failed on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:uboone/view_builds/index?offset=0&builds=uboone_ci/8209&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17601&builds=

2022-11-21 17:37 UTC, FNALbuild commented
+argoneut tests OK on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:argoneut/view_builds/index?offset=0&builds=argoneut_ci/7671&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17601&builds=

2022-11-21 17:53 UTC, FNALbuild commented
-sbnd tests warning, with build warning,, with ignored warning for build, on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:sbnd/view_builds/index?offset=0&builds=sbnd_ci/10703&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17601&builds=

2022-11-21 18:24 UTC, FNALbuild commented
-icarus tests warning, with build warning,, with ignored warning for build, on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:icarus/view_builds/index?offset=0&builds=icarus_ci/5741&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17601&builds=

2022-11-28 19:07 UTC, knoepfel reviewed
@Healthborn, thank you for your contribution.  I have a few comments for your consideration.

2022-11-28 19:07 UTC, knoepfel commented on larana/OpticalDetector/PhotonInf_module.cc
> +    std::cout << "Open log file " << LogFileName << std::endl;
If you require writing to `std::cout`, please wrap it in a verbosity flag so that users can disable it as necessary (e.g.):

```cpp
if (verbose) {
  std::cout << ...;
}
```
Please apply the same treatment to all other `std::cout` statements in this file.

2022-11-28 19:07 UTC, knoepfel commented on larana/OpticalDetector/PhotonInf_module.cc
> +        if ((*ph_handle).size() > 0) {
Suggest reversing the sign of this check to remove one level of indentation:

```cpp
if (ph_handle->empty()) {
  continue;
}
```

2022-11-28 19:07 UTC, knoepfel commented on larana/OpticalDetector/PhotonInf_module.cc
> +              //                            }
Please remove commented-out code.

2022-11-28 19:07 UTC, knoepfel commented on larana/OpticalDetector/PhotonInf_module.cc
> +    if (photon_handles.size() == 0) {
```suggestion
    if (photon_handles.empty()) {
```

2022-11-28 19:07 UTC, knoepfel commented on larana/OpticalDetector/PhotonInf_module.cc
> +                rec = true;
It seems that the purpose of all of these `for` loops is to find a photon such that `rec` can be true.  Unfortunately, after `rec` is set to true, the `for` loops continue until all of the loop iterations are done.  I think you probably want to stop iterating through all the loops once you have a match.  If this is true, then I suggest creating a separate function you can invoke where once you have a match, `return true` is executed.  For example:

```cpp
bool findMatch(art::Event const& e, std::vector<std::string> const& inputModules)
{
  auto photon_handles = evt.getMany<std::vector<sim::SimPhotons>>();
  for (...) {
    // ...
    for (...) {
      if (...) {
        pos[0] = ...;
        pos[1] = ...;
        pos[2] = ...;
        return true;
      } 
    }
  }
  return false;
}
```

And then you would do something like:
```cpp
bool const rec = findMatch(e, InputModules);
if (rec) {
  if (Filltree) { ... }
  ...
}
```

Make sense?

2022-11-28 19:07 UTC, knoepfel commented on larana/OpticalDetector/PhotonInf_module.cc
> +    }
Because this is a new module in LArSoft and no backwards compatibility is required, I suggest supporting only the vector case:

```cpp
InputModules = pset.get<std::vector<std::string>>("InputModules", {"largeant"});
```
Notice the plural form: InputModule**s**.

2022-11-28 19:23 UTC, Healthborn commented
Thank you @knoepfel for the good suggestions. I will update the code accordingly.

2022-12-05 16:33 UTC, knoepfel commented
@Healthborn, have you had a chance to implement the changes yet?

2022-12-05 16:45 UTC, Healthborn commented
@knoepfel, yes, I'm doing that. I found I also need to update the CMakefile.
I will finish everything by today.

2022-12-05 19:46 UTC, FNALbuild commented
Pull request #22 was updated. @LArSoft/level-1-managers, @LArSoft/level-2-managers can you please check and sign again.

2022-12-05 19:46 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2022-12-05 19:47 UTC, FNALbuild commented
-code-checks
Pull request failed code-formatting checks. Please ensure that `cetmodules` has been setup and execute the following command from the top-level directory of your repository:

```
format-code \
  larana/OpticalDetector/PhotonInf_module.cc
```
Then commit the changes and push them to your PR branch.

2022-12-05 19:54 UTC, FNALbuild commented
Pull request #22 was updated. @LArSoft/level-1-managers, @LArSoft/level-2-managers can you please check and sign again.

2022-12-05 19:54 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2022-12-05 19:55 UTC, FNALbuild commented
+code-checks

2022-12-05 20:00 UTC, Healthborn commented
@knoepfel,
I have made the changes accordingly. Except for the "rec = true;". I add an if-statement to make sure that the "pos" and "rec" will be assigned with values once.
The loop should be continued.

2022-12-05 20:44 UTC, knoepfel commented
trigger build

2022-12-05 20:44 UTC, FNALbuild commented
The tests are being triggered in jenkins.

2022-12-05 20:52 UTC, FNALbuild commented
-LArSoft tests failed on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17740&builds= 
 -build

2022-12-05 20:52 UTC, FNALbuild commented
-LArSoft tests failed on slf7 for c7:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17741&builds= 
 -build

2022-12-06 03:07 UTC, lgarren requested changes
You are missing a parentheses in line 296 of CMakeLists.txt  It should read
cet_build_plugin (PhotonInf art::EDAnalyzer

2022-12-06 15:15 UTC, FNALbuild commented
Pull request #22 was updated. @LArSoft/level-1-managers, @LArSoft/level-2-managers can you please check and sign again.

2022-12-06 15:15 UTC, FNALbuild commented
The code-checks are being triggered in jenkins.

2022-12-06 15:15 UTC, FNALbuild commented
+code-checks

2022-12-06 15:40 UTC, lgarren approved these changes

2022-12-06 15:41 UTC, lgarren commented
trigger build

2022-12-06 15:41 UTC, FNALbuild commented
The tests are being triggered in jenkins.

2022-12-06 16:18 UTC, FNALbuild commented
+LArSoft tests OK on slf7 for c7:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17756&builds= 
 +build

2022-12-06 16:20 UTC, FNALbuild commented
+LArSoft tests OK on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17757&builds= 
 +build

2022-12-06 16:33 UTC, FNALbuild commented
-lariat failed on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:lariat/view_builds/index?offset=0&builds=lariat_ci/7434&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17757&builds=

2022-12-06 16:34 UTC, FNALbuild commented
-uboone tests failed on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:uboone/view_builds/index?offset=0&builds=uboone_ci/8272&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17757&builds=

2022-12-06 16:38 UTC, FNALbuild commented
+argoneut tests OK on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:argoneut/view_builds/index?offset=0&builds=argoneut_ci/7734&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17757&builds=

2022-12-06 16:58 UTC, FNALbuild commented
-sbnd tests warning, with build warning,, with ignored warning for build, on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:sbnd/view_builds/index?offset=0&builds=sbnd_ci/10790&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17757&builds=

2022-12-06 17:15 UTC, FNALbuild commented
-dune tests tests warning on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:dune/view_builds/index?offset=0&builds=dune_ci/14510&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17757&builds=

2022-12-06 18:04 UTC, FNALbuild commented
-icarus tests warning, with build warning,, with ignored warning for build, on slf7 for e20:prof 
 for details see 
 https://lar-ci-history.fnal.gov/LarCI/app/ns:icarus/view_builds/index?offset=0&builds=icarus_ci/5899&builds= 
 for details of the parent CI build see 
 https://lar-ci-history.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17757&builds=

2022-12-08 00:01 UTC, tomjunk commented
Approved

Looks like the loops that find a photon with rec = true also increment counters so it is good to keep it the way it is.  It might make a big logfile, but that's up to the user to deal with.

2022-12-08 00:02 UTC, FNALbuild commented
This pull request is fully signed and it will be merged to develop and built in the next LArSoft release after it passes the integration tests. This pull request will now be reviewed by the release team before it's merged.)

2022-12-08 02:25 UTC, lgarren commented
approve

2022-12-08 02:25 UTC, merged